[package]
edition = "2021"
name = "elsm"
version = "0.1.0"

[dependencies]
async-lock = "3.3.0"
async-stream = "0.3"
crc32fast = "1"
crossbeam-skiplist = "0.1.3"
futures = "0.3"
pin-project-lite = "0.2"
thiserror = "1"
